// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/profile.get').default>>>>
    }
    '/api/admin/sql-console/execute': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/sql-console/execute.post').default>>>>
    }
    '/api/auth/impersonation/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/impersonation/start.post').default>>>>
    }
    '/api/auth/impersonation/stop': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/impersonation/stop.post').default>>>>
    }
    '/api/auth/local-handoff': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/local-handoff.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/onboarding': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/onboarding.post').default>>>>
    }
    '/api/auth/planteles-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/planteles-status.get').default>>>>
    }
    '/api/auth/switch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/switch.post').default>>>>
    }
    '/api/cfdi/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cfdi/[...path]').default>>>>
    }
    '/api/conceptos-config/admin': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/admin.get').default>>>>
    }
    '/api/conceptos-config/all': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/all.get').default>>>>
    }
    '/api/conceptos-config/current-cycle': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/current-cycle.put').default>>>>
    }
    '/api/conceptos-config/cycles/:ciclo': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/cycles/[ciclo].delete').default>>>>
    }
    '/api/conceptos-config/cycles': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/cycles/index.post').default>>>>
    }
    '/api/conceptos-config/mappings/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/mappings/[id].delete').default>>>>
    }
    '/api/conceptos-config/mappings': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/mappings/index.post').default>>>>
    }
    '/api/conceptos-config/services': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/services/index.post').default>>>>
    }
    '/api/conceptos-config/sync/central-to-bridge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos-config/sync/central-to-bridge.post').default>>>>
    }
    '/api/conceptos': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/conceptos/index').default>>>>
    }
    '/api/control-escolar/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/audit/index.get').default>>>>
    }
    '/api/control-escolar/audit/snapshot': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/audit/snapshot.post').default>>>>
    }
    '/api/control-escolar/cache/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/cache/status.get').default>>>>
    }
    '/api/control-escolar/enrollment-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/enrollment-config.get').default>>>>
    }
    '/api/control-escolar/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/export.get').default>>>>
    }
    '/api/control-escolar/kpis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/kpis.get').default>>>>
    }
    '/api/control-escolar/matricula-db/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/matricula-db/export.get').default>>>>
    }
    '/api/control-escolar/matricula-db/import': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/matricula-db/import.post').default>>>>
    }
    '/api/control-escolar/options': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/options.get').default>>>>
    }
    '/api/control-escolar/students/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/students/[id].patch').default>>>>
    }
    '/api/control-escolar/students/:id/husky-pass-email': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/students/[id]/husky-pass-email.post').default>>>>
    }
    '/api/control-escolar/students/:id/siblings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/students/[id]/siblings.get').default>>>>
    }
    '/api/control-escolar/students': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/control-escolar/students/index.get').default>>>>
    }
    '/api/dashboard/kpis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/kpis.get').default>>>>
    }
    '/api/debug/db-context': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/db-context.get').default>>>>
    }
    '/api/debug/users-external': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/debug/users-external.get').default>>>>
    }
    '/api/deudores/actions': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/actions.post').default>>>>
    }
    '/api/deudores/email-preview': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/email-preview.post').default>>>>
    }
    '/api/deudores/excepciones': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/excepciones.post').default>>>>
    }
    '/api/deudores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/index.get').default>>>>
    }
    '/api/deudores/observaciones': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/observaciones.post').default>>>>
    }
    '/api/deudores/template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/template.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/deudores/template.post').default>>>>
    }
    '/api/directory/photo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/photo.get').default>>>>
    }
    '/api/directory/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/users.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/directory/users.post').default>>>>
    }
    '/api/documentos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/[id].delete').default>>>>
    }
    '/api/documentos/:id/beca-carta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/[id]/beca-carta.get').default>>>>
    }
    '/api/documentos/:id/concepto': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/[id]/concepto.put').default>>>>
    }
    '/api/documentos/:id/monto': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/[id]/monto.put').default>>>>
    }
    '/api/documentos': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/index.post').default>>>>
    }
    '/api/documentos/monto-final': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/monto-final.post').default>>>>
    }
    '/api/documentos/period': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/documentos/period.post').default>>>>
    }
    '/api/downloadInvoice/:id/:format': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/downloadInvoice/[id]/[format].get').default>>>>
    }
    '/api/external/v1/control-escolar/auth/diagnostics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/auth/diagnostics.get').default>>>>
    }
    '/api/external/v1/control-escolar/auth/echo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/auth/echo.get').default>>>>
    }
    '/api/external/v1/control-escolar/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/health.get').default>>>>
    }
    '/api/external/v1/control-escolar/students/:matricula': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/students/[matricula].get').default>>>>
    }
    '/api/external/v1/control-escolar/students/changes': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/students/changes.get').default>>>>
    }
    '/api/external/v1/control-escolar/students': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/students/index.get').default>>>>
    }
    '/api/external/v1/control-escolar/warm': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/warm/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/control-escolar/warm/index.post').default>>>>
    }
    '/api/external/v1/deudores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/external/v1/deudores/index.get').default>>>>
    }
    '/api/getCompanyData': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getCompanyData.get').default>>>>
    }
    '/api/invoices/:id/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/[id]/cancel.post').default>>>>
    }
    '/api/invoices': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/invoices/index.post').default>>>>
    }
    '/api/login/updates': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/login/updates.get').default>>>>
    }
    '/api/no-adeudo/control-recipient': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/control-recipient.put').default>>>>
    }
    '/api/no-adeudo/control-users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/control-users.get').default>>>>
    }
    '/api/no-adeudo/diagnostics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/diagnostics.get').default>>>>
    }
    '/api/no-adeudo/pdf': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/pdf.get').default>>>>
    }
    '/api/no-adeudo/preview': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/preview.post').default>>>>
    }
    '/api/no-adeudo/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/send.post').default>>>>
    }
    '/api/no-adeudo/verify/:token': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/no-adeudo/verify/[token].get').default>>>>
    }
    '/api/payments/audit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/audit.post').default>>>>
    }
    '/api/payments/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/cancel.post').default>>>>
    }
    '/api/payments/email-receipt': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/email-receipt.post').default>>>>
    }
    '/api/payments/pay': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/pay.post').default>>>>
    }
    '/api/payments/receipt': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payments/receipt.get').default>>>>
    }
    '/api/reminders/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/batch.post').default>>>>
    }
    '/api/reminders/send': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reminders/send.post').default>>>>
    }
    '/api/reports/concepto': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/concepto.get').default>>>>
    }
    '/api/reports/corte_print': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/corte_print.get').default>>>>
    }
    '/api/reports/corte': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/corte.get').default>>>>
    }
    '/api/saveCompanyAndGenerate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/saveCompanyAndGenerate.post').default>>>>
    }
    '/api/sendInvoiceEmail': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sendInvoiceEmail.post').default>>>>
    }
    '/api/student-sections/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/student-sections/[id]/index.delete').default>>>>
    }
    '/api/student-sections': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/student-sections/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/student-sections/index.post').default>>>>
    }
    '/api/students/:matricula/control-escolar-detail': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/control-escolar-detail.get').default>>>>
    }
    '/api/students/:matricula/debts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/debts.get').default>>>>
    }
    '/api/students/:matricula': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/index').default>>>>
    }
    '/api/students/:matricula/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/info.get').default>>>>
    }
    '/api/students/:matricula/ingreso-cycle': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/ingreso-cycle.put').default>>>>
    }
    '/api/students/:matricula/matricula-overlay': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/matricula-overlay.get').default>>>>
    }
    '/api/students/:matricula/operator-info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/operator-info.get').default>>>>
    }
    '/api/students/:matricula/photo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/photo.get').default>>>>
    }
    '/api/students/:matricula/sections': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/sections.put').default>>>>
    }
    '/api/students/:matricula/servicios': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/servicios/index.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/servicios/index.put').default>>>>
    }
    '/api/students/:matricula/siblings': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/siblings.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/[matricula]/siblings.get').default>>>>
    }
    '/api/students/bulk-baja': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/bulk-baja.put').default>>>>
    }
    '/api/students/bulk-ingreso-cycle': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/bulk-ingreso-cycle.put').default>>>>
    }
    '/api/students': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/index.get').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/index').default>>>>
    }
    '/api/students/kpi-trends': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/kpi-trends.get').default>>>>
    }
    '/api/students/matricula-overlays': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/matricula-overlays.post').default>>>>
    }
    '/api/students/matricula-preview': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/matricula-preview.get').default>>>>
    }
    '/api/students/sections/bulk': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/sections/bulk.put').default>>>>
    }
    '/api/sync/base/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/base/batch.post').default>>>>
    }
    '/api/sync/base/cancel': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/base/cancel.post').default>>>>
    }
    '/api/sync/base/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/base/start.post').default>>>>
    }
    '/api/sync/base/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sync/base/status.get').default>>>>
    }
    '/api/system/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/health.get').default>>>>
    }
    '/api/system/info': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/info.get').default>>>>
    }
    '/api/system/launch': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/launch.get').default>>>>
    }
    '/api/system/local-status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/local-status.get').default>>>>
    }
    '/api/system/local-update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/local-update.post').default>>>>
    }
    '/api/system/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/system/update.post').default>>>>
    }
    '/api/talleres-servicios/catalogo': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/talleres-servicios/catalogo.get').default>>>>
    }
    '/api/users/:id': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/[id]').default>>>>
    }
    '/api/users/bulk-inverse': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/bulk-inverse').default>>>>
    }
    '/api/users/bulk': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/bulk').default>>>>
    }
    '/api/users/debug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/debug.get').default>>>>
    }
    '/api/users': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users/index').default>>>>
    }
    '/api/whatsapp/instances/:clientId/configuration': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/configuration.patch').default>>>>
    }
    '/api/whatsapp/instances/:clientId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/index.get').default>>>>
    }
    '/api/whatsapp/instances/:clientId/messages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/messages.post').default>>>>
    }
    '/api/whatsapp/instances/:clientId/qr': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/qr.get').default>>>>
    }
    '/api/whatsapp/instances/:clientId/reconnect': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/reconnect.post').default>>>>
    }
    '/api/whatsapp/instances/:clientId/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/[clientId]/status.get').default>>>>
    }
    '/api/whatsapp/instances': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/whatsapp/instances/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}