import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { stripTypeScriptTypes } from 'node:module';
const dataUrl = source => `data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
const ciclo = dataUrl(stripTypeScriptTypes(await readFile('shared/utils/ciclo.ts', 'utf8')));
const tipo = dataUrl(stripTypeScriptTypes((await readFile('shared/utils/tipoIngreso.ts', 'utf8')).replace('"./ciclo"', JSON.stringify(ciclo))));
const moduleSource = (await readFile('shared/utils/nuevoIngreso.ts', 'utf8')).replace("'./tipoIngreso'", JSON.stringify(tipo)).replace("'./ciclo'", JSON.stringify(ciclo));
const { nuevoIngresoForStudent, withNuevoIngreso } = await import(dataUrl(stripTypeScriptTypes(moduleSource)));
assert.equal(nuevoIngresoForStudent({ cicloBase: '2026' }, '2026').nuevoIngreso, true);
assert.equal(nuevoIngresoForStudent({ cicloBase: '2025' }, '2026').nuevoIngreso, false);
assert.equal(nuevoIngresoForStudent({}, '2026').nuevoIngreso, null);
assert.equal(nuevoIngresoForStudent({ cicloBase: '2027' }, '2026').nuevoIngreso, null);
assert.equal(nuevoIngresoForStudent({ cicloBase: '2026', tipoIngresoSource: 'manual_override', tipoIngresoValue: 'interno' }, '2026').nuevoIngreso, false);
assert.equal(nuevoIngresoForStudent({ cicloBase: '2026', tipoIngresoValue: 'interno' }, '2026').nuevoIngreso, false, 'Preserve canonical overrides in snapshots predating the source field');
const response = { data: [{ matricula: 'PM1', cicloBase: '2026', status: 'Activo' }], pagination: { nextCursor: 'same' }, meta: { ciclo: '2026' } };
const expanded = withNuevoIngreso(response, '2026');
assert.deepEqual(expanded.pagination, response.pagination);
assert.equal(expanded.data[0].status, 'Activo');
assert.equal(expanded.data[0].cicloIngreso, '2026-2027');
assert.equal(Object.hasOwn(response.data[0], 'nuevoIngreso'), false);
assert.equal(withNuevoIngreso({ data: { cicloBase: '2026' } }, '2026').data.nuevoIngreso, true);
console.log('Aurora: canonical enrollment rules and additive roster/detail contracts passed.');
