// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/17/2026, 12:35:40 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/hp/sistema-de-ingresos-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/plugins/**/*.{js,ts,mjs}","C:/Users/hp/sistema-de-ingresos-2/composables/**/*.{js,ts,mjs}","C:/Users/hp/sistema-de-ingresos-2/utils/**/*.{js,ts,mjs}","C:/Users/hp/sistema-de-ingresos-2/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/hp/sistema-de-ingresos-2/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;